// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetcoreSaas.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NetcoreSaas.WebApi.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("File")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LinkId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ContractActivity");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ContractEmployee");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("UserId");

                    b.ToTable("ContractMember");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Common.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeyValues")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Table")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Links.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientWorkspaceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedByWorkspaceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProviderWorkspaceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientWorkspaceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedByWorkspaceId");

                    b.HasIndex("ProviderWorkspaceId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Links.LinkInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedByWorkspaceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedLinkId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("InviteeIsProvider")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WorkspaceName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedByWorkspaceId");

                    b.HasIndex("CreatedLinkId")
                        .IsUnique();

                    b.ToTable("LinkInvitations");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Included")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionProductId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("TranslateInFrontend")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionProductId");

                    b.ToTable("SubscriptionFeatures");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PriceBefore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SubscriptionProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TrialDays")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionProductId");

                    b.ToTable("SubscriptionPrices");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Badge")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("ContactUs")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MaxLinks")
                        .HasColumnType("int");

                    b.Property<int>("MaxStorage")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<int>("MaxWorkspaces")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MonthlyContracts")
                        .HasColumnType("int");

                    b.Property<string>("ServiceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionProducts");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LogoDarkmode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Subdomain")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SubscriptionCustomerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f6db738-2a47-4cfd-8576-34af7bd0c30a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            Subdomain = "admin",
                            Uuid = new Guid("e2b9a8de-2196-11eb-adc1-0242ac120002")
                        });
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantJoinSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Link")
                        .HasColumnType("char(36)");

                    b.Property<bool>("LinkActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PublicUrl")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequireAcceptance")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantJoinSettings");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLinks")
                        .HasColumnType("int");

                    b.Property<int>("MaxStorage")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<int>("MaxWorkspaces")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MonthlyContracts")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubscriptionPriceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubscriptionServiceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPriceId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantProducts");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChatbotCustomerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("InvitationLink")
                        .HasColumnType("char(36)");

                    b.Property<int>("Joined")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("999894d7-412b-4e4a-bcae-4d59bbd9ad6f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailNotifications = true,
                            Joined = 0,
                            Role = 0,
                            Status = 2,
                            TenantId = new Guid("3f6db738-2a47-4cfd-8576-34af7bd0c30a"),
                            UserId = new Guid("5dfffe8c-3f67-4ffc-9b54-fbf5e0247382")
                        });
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DefaultTenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Locale")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("Token")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dfffe8c-3f67-4ffc-9b54-fbf5e0247382"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "DEVELOPMENT_ADMIN_EMAIL",
                            FirstName = "Admin",
                            Gender = "M",
                            LastName = "User",
                            LoginType = 0,
                            Password = "AVgYX8iuxa+kVg8zJ1eNC0yu8hI6Kf8MUY6RVQajSvCPV6XXSvr7z0xroWBx6L/2Dg==",
                            Token = new Guid("fc5a0877-2888-4723-a60a-361a7a02d038"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessMainActivity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5418bcc9-2d34-47d6-9b64-c9f48a3cd9e5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Default = false,
                            Name = "Default Workspace",
                            TenantId = new Guid("3f6db738-2a47-4cfd-8576-34af7bd0c30a"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Workspaces.WorkspaceUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e10a59cf-d03d-4756-874d-22946c22d12c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Default = false,
                            Role = 0,
                            UserId = new Guid("5dfffe8c-3f67-4ffc-9b54-fbf5e0247382"),
                            WorkspaceId = new Guid("5418bcc9-2d34-47d6-9b64-c9f48a3cd9e5")
                        });
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.Contract", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Links.Link", "Link")
                        .WithMany("Contracts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractActivity", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.App.Contracts.Contract", "Contract")
                        .WithMany("Activity")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractEmployee", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.App.Contracts.Contract", null)
                        .WithMany("Employees")
                        .HasForeignKey("ContractId");

                    b.HasOne("NetcoreSaas.Domain.Models.App.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.ContractMember", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.App.Contracts.Contract", "Contract")
                        .WithMany("Members")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Employees.Employee", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Links.Link", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "ClientWorkspace")
                        .WithMany()
                        .HasForeignKey("ClientWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "CreatedByWorkspace")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "ProviderWorkspace")
                        .WithMany()
                        .HasForeignKey("ProviderWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientWorkspace");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedByWorkspace");

                    b.Navigation("ProviderWorkspace");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Links.LinkInvitation", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "CreatedByWorkspace")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Links.Link", "CreatedLink")
                        .WithOne("LinkInvitation")
                        .HasForeignKey("NetcoreSaas.Domain.Models.Core.Links.LinkInvitation", "CreatedLinkId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedByWorkspace");

                    b.Navigation("CreatedLink");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionFeature", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionProduct", "SubscriptionProduct")
                        .WithMany("Features")
                        .HasForeignKey("SubscriptionProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionProduct");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionPrice", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionProduct", "SubscriptionProduct")
                        .WithMany("Prices")
                        .HasForeignKey("SubscriptionProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionProduct");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantJoinSettings", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "Tenant")
                        .WithOne("TenantJoinSettings")
                        .HasForeignKey("NetcoreSaas.Domain.Models.Core.Tenants.TenantJoinSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantProduct", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionPrice", "SubscriptionPrice")
                        .WithMany()
                        .HasForeignKey("SubscriptionPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPrice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.TenantUser", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "User")
                        .WithMany("Tenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Users.User", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "DefaultTenant")
                        .WithMany()
                        .HasForeignKey("DefaultTenantId");

                    b.Navigation("DefaultTenant");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", "Tenant")
                        .WithMany("Workspaces")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Workspaces.WorkspaceUser", b =>
                {
                    b.HasOne("NetcoreSaas.Domain.Models.Core.Users.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", "Workspace")
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.App.Contracts.Contract", b =>
                {
                    b.Navigation("Activity");

                    b.Navigation("Employees");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Links.Link", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("LinkInvitation");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Subscriptions.SubscriptionProduct", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Tenants.Tenant", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("TenantJoinSettings");

                    b.Navigation("Users");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Users.User", b =>
                {
                    b.Navigation("Tenants");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("NetcoreSaas.Domain.Models.Core.Workspaces.Workspace", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
